name: zloop

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04
    env:
      TEST_DIR: /var/tmp/zloop
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: |
        # https://github.com/orgs/community/discussions/47863
        sudo apt-mark hold grub-efi-amd64-signed
        sudo apt-get update --fix-missing
        sudo apt-get upgrade
        sudo xargs --arg-file=${{ github.workspace }}/.github/workflows/build-dependencies.txt apt-get install -qq
        sudo apt-get clean
    - name: Autogen.sh
      run: |
        sh autogen.sh
    - name: Configure
      run: |
        ./configure --enable-debug --enable-debuginfo
    - name: Make
      run: |
        # Hack for zfs-2.1.16+
        #
        # When Alien converts the RPMs to DEB packages, it calls this line:
        #
        # $this->do("rpm2cpio '".$this->filename."' | (cd $workdir; $decomp cpio
        #     --extract --make-directories --no-absolute-filenames
        #     --preserve-modification-time) 2>&1")
        #
        # This seems to fail with zfs-2.1.16 with:
        #
        #    cpio: ./usr/src/spl-2.1.16/6.5.0-1025-azure: Cannot open: No such file or directory
        #
        # The workaround is just to always return true from the 'cpio' command.
        # This does not seem to affect anything.
        sudo sed -i 's/preserve-modification-time/preserve-modification-time | true/g' /usr/share/perl5/Alien/Package/Rpm.pm

        make --no-print-directory -s pkg-utils pkg-kmod
    - name: Install
      run: |
        sudo dpkg -i *.deb
        # Update order of directories to search for modules, otherwise
        #   Ubuntu will load kernel-shipped ones.
        sudo sed -i.bak 's/updates/extra updates/' /etc/depmod.d/ubuntu.conf
        sudo depmod
        sudo modprobe zfs
    - name: Tests
      run: |
        sudo mkdir -p $TEST_DIR
        # run for 10 minutes or at most 2 iterations for a maximum runner
        #   time of 20 minutes.
        sudo /usr/share/zfs/zloop.sh -t 600 -I 2 -l -m1 -- -T 120 -P 60
    - name: Prepare artifacts
      if: failure()
      run: |
        sudo chmod +r -R $TEST_DIR/
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Logs
        path: |
          /var/tmp/zloop/*/
          !/var/tmp/zloop/*/vdev/
        if-no-files-found: ignore
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Pool files
        path: |
          /var/tmp/zloop/*/vdev/
        if-no-files-found: ignore
